### ISSUE TITLE
Update for pysigma 0.9.* ?

### ISSUE THREAD

**Issue by Asilias** [SigmaHQ/pySigma-backend-elasticsearch#16]
Hi,

First, I would like to thank you both for your amazing work around pysigma.

I would like to know if there is a scheduled update to make the pysigma-backend-elasticsearch module compatible with pysigma 0.9.0 and more?

My issue is that I would like to use  Qradar, Splunk and Elasticsearch backends together but the elastic one is the unique one uncompatible with version of pysigma over 0.8.12.

For now, I'm downgrading versions of all packages to match with this elasticsearch backend so it isn't really an issue, more a question.

Thank you both again for all your arduous work.

Best regards,

**Comment by thomaspatzke** [comment]
Thanks for bringing this up. We were aware but forgot about this. Now there's a 1.0.0 version that is compatible with pySigma 0.9. I've also updated the plugin directory, so it should be installable with `sigma plugin install elasticsearch` from the CLI.
