### ISSUE TITLE
Missing case-insensitive options

### ISSUE THREAD

**Issue by cospirho** [SigmaHQ/pySigma-backend-elasticsearch#21]
The legacy converter had the options:
 - `case_insensitive_whitelist`
 - `case_insensitive_blacklist`
 
I don't see a way to enable similar functionality in the current backend.
These options are necessary to perform case insensitive searches on keyword fields. The (?i) syntax is not supported.
In the current default winlogbeat fields.yml, there are many fields used in rules that are keyword only that need to be case insensitive.

Thanks!

**Comment by Technici4n** [comment]
I solved this by adding a lowercase normalizer to the relevant fields - not ideal but I am not sure that the `query_text` query supports case insensitive searches.
