### ISSUE TITLE
ecs_windows can not be use with lucene 

### ISSUE THREAD

**Issue by frack113** [SigmaHQ/pySigma-backend-elasticsearch#31]
I can ot use `elasticsearch` as backend 
`error: Invalid value for '--target' / '-t': 'elasticsearch' is not one of 'lucene', 'splunk'. - run sigma plugin list --plugin-type backend for a list of available plugins.`

So with lucene  `sigma convert -t lucene -p sysmon -p ecs_windows -p./elastalert_any.yml ./proc_creation_win_7zip_password_compression.yml`
get a error : 'ecs_windows' is not intended to be used with the target lucene.

I have to use `--disable-pipeline-check` to get a lucene query with ECS

**Comment by thomaspatzke** [comment]
Fixed, preparing the release.
