### ISSUE TITLE
Elastalert backend

### ISSUE THREAD

**Issue by m4dh4t** [SigmaHQ/pySigma-backend-elasticsearch#75]
Hi.

@kurisukun and myself drafted a backend converting Sigma rules into Elastalert rules, inheriting from `LuceneBackend`. It currently supports simple rules as well as the `event_count` and `value_count` correlation rules. You can find the relevant code here: https://github.com/m4dh4t/pySigma-backend-elasticsearch/tree/feat-elastalert-backend

Would you @andurin be interested in this being merged in pySigma-backend-elasticsearch as this backend was originally supported by `sigmac` ? I think it would make sense as this backend is strongly linked to Elasticsearch.

If not, we will create a dedicated repository for it.

**Comment by andurin** [comment]
As already discussed via discord I would be happy to see a Merge-Request since the rule/query building block is quite the same and this will be another inherited backend.

**Comment by m4dh4t** [comment]
I need to do a last check with @kurisukun to make sure everything is in order, will probably open the PR tomorrow !

**Comment by m4dh4t** [comment]
Adressed by https://github.com/SigmaHQ/pySigma-backend-elasticsearch/pull/95
